### ISSUE TITLE
 No such file or directory: 'data/font_emb/mfc.pkl'

### ISSUE THREAD

**Issue by linlb11** [CyberAgentAILab/tdc-typography-generation#2]
Hi, I encountered this error "No such file or directory: 'data/font_emb/mfc.pkl'" when running the command of training. It seems that mfc.pkl is missing.

**Comment by wandonye** [comment]
Getting the same error. Is this just one hot encoding or what?
From the paper, it seems font is a categorical input, so nothing more than one hot encoding should be used.
But the file name `mfc.pkl` is suggesting something fancier.

**Comment by shimoda-uec** [comment]
I am sorry for the error.
The pickle file is one hot encoding and is for a compared method.
The error due to the absence of the file is what I did not expect.
I will fix it.
